name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }} # runs a test on Ubuntu, Windows and macOS

    strategy:
      matrix:
        deno: [ "v1.x", "nightly" ]
        os: [ macOS-latest, windows-latest, ubuntu-latest ]

    steps:
      - name: Setup repo
        uses: actions/checkout@v2

      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run Tests
        run: deno test ./tests/mod.ts -A --unstable

      - name: Lint files
        run: deno lint --unstable
